### PR TITLE
bigstringaf: switch to using bigstringaf

### PR DESCRIPTION
**Pull request by seliopou**

### CODE REVIEW

**Comment by hcarty** [comment]
Looks good to me!  Nice to have this factored out and usable externally - thanks!

**Comment by hannesm** [comment]
just me being curious, but is there any benchmark difference before and after (i understand that in theory there shouldn't be any)

**Comment by hcarty** [comment]
@hannesm FWIW I ran some internal benchmarks before/after this PR and saw no significant change in those tests.

**Comment by seliopou** [comment]
This was motivated by httpaf benchmarks. In particular I was running perf on `wrk_async_benchmark.exe` during a load test and saw a bunch of C calls and `caml_ba_set_1`'s, which were coming from the Faraday `Bigstring` module, which I hadn't been paying as much attention to as Angstrom's.

**Comment by seliopou** [comment]
So to be clear, there shouldn't be a difference in Angstom, but there should be a measurable difference in Faraday.

**Comment by hcarty** [comment]
FWIW - I had my pins setup incorrectly in my tests.  There is a nice speedup with this change.

**Pull request merged**
