### PR TITLE
Fix compatibility with core >= 0.15

### PR DESCRIPTION
**Pull request by bcc32**
Just fixes for the removal of `Core.Unix` in 0.15

### CODE REVIEW

**Comment by vbmithr** [comment]
It was also blocking upgrade to Core v0.15, which caused other problems for my use cases…

**Comment by vbmithr** [comment]
@seliopou Could we merge this?

**Comment by seliopou** [comment]
The build appears to be broken.

**Comment by bcc32** [comment]
Ah, right.  Async 0.14 doesn't depend on Core_unix, so I needed to add something to the dune file.

**Pull request merged**
