### PR TITLE
unsafe_set_*_(le,be) were swapped

### PR DESCRIPTION
**Pull request by hcarty**

### CODE REVIEW

**Comment by hcarty** [comment]
Thanks!

**Comment by seliopou** [comment]
Ugh, that was embarrassing. Thanks for the fix and the tests.

**Comment by hcarty** [comment]
Those kinds of single-character typos are a nasty batch of potential bugs - happy to help where I can

**Comment by seliopou** [comment]
Fixes problems that were introduced in #24.

**Pull request merged**
